<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MeiErp.Platform.Printing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MeiErp.Platform.Kernel\MeiErp.Platform.Kernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="ZXing.Net" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>
</Project>
