<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MeiErp.Platform.Identity.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\platform\MeiErp.Platform.Identity\MeiErp.Platform.Identity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Xunit.SkippableFact" />
  </ItemGroup>
</Project>
