<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <RootNamespace>MeiErp.Platform.Web</RootNamespace>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MeiErp.Platform.Kernel\MeiErp.Platform.Kernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>
</Project>
