using MeiErp.Platform.Printing;
using MeiErp.Platform.Reporting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MeiErp.Modules.Inventory;

public static class InventoryReports
{
    public static IServiceCollection AddInventoryReports(this IServiceCollection services)
    {
        foreach(var factory in new Func<IServiceProvider,ReportDefinition>[] {StockLevels,Valuation,LowStock,ByWarehouse,Serials,Batches,Movements})services.AddSingleton(sp=>factory(sp));return services;
    }
    private static ReportRow Row(string? url,params(string Key,object? Value)[] values)=>new(values.ToDictionary(x=>x.Key,x=>x.Value),url);
    private static ReportDefinition StockLevels(IServiceProvider sp)=>new(){Key="inventory.stock-levels",Name="Stock levels",Description="Everything on hand, with reorder levels.",ModuleKey=InventoryModule.Key,Group="Stock",Permission=InventoryModule.ReportsView,Uses=ReportFilters.Item,SortOrder=1,Run=async(r,ct)=>{var q=sp.GetRequiredService<InventoryDbContext>().Items.AsNoTracking().Include(x=>x.ProductFamily).Include(x=>x.ParentItem).AsQueryable();if(r.ItemId is { } id)q=q.Where(x=>x.Id==id);var rows=await q.OrderBy(x=>x.Name).ToListAsync(ct);return new(){Columns=[new("family","Product",ReportValueKind.Text,2),new("item","Item",ReportValueKind.Text,3),new("kind","Kind",ReportValueKind.Status,1),new("unit","Unit"),new("qty","On hand",ReportValueKind.Number),new("reorder","Reorder at",ReportValueKind.Number),new("status","Status",ReportValueKind.Status)],Rows=[..rows.Select(x=>Row("/inventory/items",("family",x.ProductFamily?.Name??"Unclassified"),("item",x.ParentItem is null?x.Name:$"{x.ParentItem.Name} › {x.Name}"),("kind",x.Kind.ToString()),("unit",x.Unit),("qty",x.QuantityOnHand),("reorder",x.ReorderLevel),("status",x.ReorderLevel>0&&x.QuantityOnHand<=x.ReorderLevel?"LOW":"OK")))],Totals=[new("qty",rows.Sum(x=>x.QuantityOnHand))]};}};
    private static ReportDefinition Valuation(IServiceProvider sp)=>new(){Key="inventory.valuation",Name="Stock valuation",Description="On-hand stock at weighted-average cost.",ModuleKey=InventoryModule.Key,Group="Stock",Permission=InventoryModule.CostsView,Uses=ReportFilters.None,SortOrder=2,Run=async(_,ct)=>{var rows=await sp.GetRequiredService<InventoryDbContext>().Items.AsNoTracking().Include(x=>x.ProductFamily).OrderBy(x=>x.Name).ToListAsync(ct);return new(){Columns=[new("product","Product",ReportValueKind.Text,2),new("item","Item",ReportValueKind.Text,3),new("qty","Qty",ReportValueKind.Number),new("cost","Avg cost",ReportValueKind.Money),new("value","Value",ReportValueKind.Money),new("sale","Sale price",ReportValueKind.Money)],Rows=[..rows.Select(x=>Row("/inventory/items",("product",x.ProductFamily?.Name??"Unclassified"),("item",x.Name),("qty",x.QuantityOnHand),("cost",x.AverageCost),("value",x.StockValue),("sale",x.SellingPrice)))],Totals=[new("qty",rows.Sum(x=>x.QuantityOnHand)),new("value",rows.Sum(x=>x.StockValue))],Header=[new PrintField("Basis","Weighted-average cost") ]};}};
    private static ReportDefinition LowStock(IServiceProvider sp)=>new(){Key="inventory.low-stock",Name="Low stock",Description="Items at or below reorder level.",ModuleKey=InventoryModule.Key,Group="Stock",Permission=InventoryModule.ReportsView,Uses=ReportFilters.None,SortOrder=3,Run=async(_,ct)=>{var rows=await sp.GetRequiredService<InventoryDbContext>().Items.AsNoTracking().Where(x=>x.IsActive&&x.ReorderLevel>0&&x.QuantityOnHand<=x.ReorderLevel).OrderBy(x=>x.Name).ToListAsync(ct);return new(){Columns=[new("item","Item",ReportValueKind.Text,3),new("qty","On hand",ReportValueKind.Number),new("level","Reorder at",ReportValueKind.Number),new("buy","Suggested buy",ReportValueKind.Number),new("short","Short by",ReportValueKind.Number)],Rows=[..rows.Select(x=>Row("/inventory/items",("item",x.Code+" — "+x.Name),("qty",x.QuantityOnHand),("level",x.ReorderLevel),("buy",x.ReorderQuantity),("short",Math.Max(0,x.ReorderLevel-x.QuantityOnHand))))]};}};
    private static ReportDefinition ByWarehouse(IServiceProvider sp)=>new(){Key="inventory.by-warehouse",Name="Stock by warehouse",Description="Where stock physically sits.",ModuleKey=InventoryModule.Key,Group="Stock",Permission=InventoryModule.ReportsView,Uses=ReportFilters.Item,SortOrder=4,Run=async(r,ct)=>{var q=sp.GetRequiredService<InventoryDbContext>().WarehouseBalances.AsNoTracking().Include(x=>x.Warehouse).Include(x=>x.Item).Where(x=>x.Quantity!=0);if(r.ItemId is { } id)q=q.Where(x=>x.ItemId==id);var rows=await q.OrderBy(x=>x.Warehouse!.Name).ThenBy(x=>x.Item!.Name).ToListAsync(ct);return new(){Columns=[new("warehouse","Warehouse",ReportValueKind.Text,2),new("item","Item",ReportValueKind.Text,3),new("qty","Quantity",ReportValueKind.Number),new("unit","Unit")],Rows=[..rows.Select(x=>Row("/inventory/warehouses",("warehouse",x.Warehouse!.Name),("item",x.Item!.Name),("qty",x.Quantity),("unit",x.Item.Unit)))],Totals=[new("qty",rows.Sum(x=>x.Quantity))]};}};
    private static ReportDefinition Serials(IServiceProvider sp)=>new(){Key="inventory.serials",Name="Serialized units",Description="Every individually tracked unit and status.",ModuleKey=InventoryModule.Key,Group="Tracking",Permission=InventoryModule.ReportsView,Uses=ReportFilters.Item|ReportFilters.Status,SortOrder=5,Run=async(r,ct)=>{var q=sp.GetRequiredService<InventoryDbContext>().StockUnits.AsNoTracking().Include(x=>x.Item).Include(x=>x.Warehouse).Include(x=>x.Batch).AsQueryable();if(r.ItemId is { } id)q=q.Where(x=>x.ItemId==id);if(Enum.TryParse<StockUnitStatus>(r.Status,true,out var status))q=q.Where(x=>x.Status==status);var rows=await q.OrderBy(x=>x.Status).ThenBy(x=>x.SerialNumber).Take(5000).ToListAsync(ct);return new(){Columns=[new("item","Item",ReportValueKind.Text,2.5f),new("serial","Serial",ReportValueKind.Text,2),new("status","Status",ReportValueKind.Status),new("warehouse","Warehouse",ReportValueKind.Text,1.5f),new("batch","Batch"),new("received","Received",ReportValueKind.Date),new("issued","Issued to",ReportValueKind.Text,1.5f)],Rows=[..rows.Select(x=>Row("/inventory/tracking",("item",x.Item!.Name),("serial",x.SerialNumber),("status",x.Status.ToString()),("warehouse",x.Warehouse?.Name),("batch",x.Batch?.BatchNumber),("received",x.ReceivedOn),("issued",x.IssuedTo)))]};}};
    private static ReportDefinition Batches(IServiceProvider sp)=>new(){Key="inventory.batches",Name="Batches and expiry",Description="Open batches in expiry order.",ModuleKey=InventoryModule.Key,Group="Tracking",Permission=InventoryModule.ReportsView,Uses=ReportFilters.Item,SortOrder=6,Run=async(r,ct)=>{var q=sp.GetRequiredService<InventoryDbContext>().StockBatches.AsNoTracking().Include(x=>x.Item).Include(x=>x.Warehouse).Where(x=>x.RemainingQuantity>0);if(r.ItemId is { } id)q=q.Where(x=>x.ItemId==id);var rows=await q.OrderBy(x=>x.ExpiresOn??DateOnly.MaxValue).ToListAsync(ct);var today=sp.GetRequiredService<MeiErp.Platform.Kernel.IClock>().Today;return new(){Columns=[new("item","Item",ReportValueKind.Text,2.5f),new("batch","Batch",ReportValueKind.Text,1.5f),new("warehouse","Warehouse",ReportValueKind.Text,1.5f),new("received","Received",ReportValueKind.Date),new("expires","Expires",ReportValueKind.Date),new("original","Original",ReportValueKind.Number),new("remaining","Remaining",ReportValueKind.Number),new("status","Status",ReportValueKind.Status)],Rows=[..rows.Select(x=>Row("/inventory/tracking",("item",x.Item!.Name),("batch",x.BatchNumber),("warehouse",x.Warehouse!.Name),("received",x.ReceivedOn),("expires",x.ExpiresOn),("original",x.Quantity),("remaining",x.RemainingQuantity),("status",x.IsExpired(today)?"EXPIRED":"OK")))],Totals=[new("remaining",rows.Sum(x=>x.RemainingQuantity))]};}};
    private static ReportDefinition Movements(IServiceProvider sp)=>new(){Key="inventory.movements",Name="Stock movements",Description="Append-only stock ledger.",ModuleKey=InventoryModule.Key,Group="Audit",Permission=InventoryModule.ReportsView,Uses=ReportFilters.DateRange|ReportFilters.Item,SortOrder=7,Run=async(r,ct)=>{var today=sp.GetRequiredService<MeiErp.Platform.Kernel.IClock>().Today;var from=r.From??today.AddMonths(-1);var to=r.To??today;var q=sp.GetRequiredService<InventoryDbContext>().StockMovements.AsNoTracking().Include(x=>x.Warehouse).Where(x=>x.Date>=from&&x.Date<=to);if(r.ItemId is { } id)q=q.Where(x=>x.ItemId==id);var rows=await q.OrderByDescending(x=>x.Date).ThenByDescending(x=>x.Id).Take(5000).ToListAsync(ct);return new(){Columns=[new("date","Date",ReportValueKind.Date),new("item","Item",ReportValueKind.Text,2.5f),new("warehouse","Warehouse",ReportValueKind.Text,1.5f),new("type","Type",ReportValueKind.Status),new("qty","Quantity",ReportValueKind.Number),new("balance","Balance",ReportValueKind.Number),new("reference","Reference",ReportValueKind.Text,1.5f),new("notes","Notes",ReportValueKind.Text,2)],Rows=[..rows.Select(x=>Row("/inventory/items",("date",x.Date),("item",x.ItemCode+" — "+x.ItemName),("warehouse",x.Warehouse?.Name),("type",x.Type.ToString()),("qty",x.Quantity),("balance",x.BalanceAfter),("reference",x.Reference),("notes",x.Narration)))],Totals=[new("qty",rows.Sum(x=>x.Quantity))]};}};
}
