using MeiErp.Platform.Kernel;
using Microsoft.EntityFrameworkCore;

namespace MeiErp.Modules.Inventory;

public enum InventoryReturnKind{SalesReturn,PurchaseReturn}
public class InventoryReturn:AuditableEntity
{
    public string Number{get;set;}="";public DateOnly Date{get;set;}public InventoryReturnKind Kind{get;set;}/// <summary>
    /// The customer or supplier, as an id plus a name snapshot. No foreign key:
    /// the party master belongs to Sales &amp; Purchase, in another schema, and
    /// this platform never puts a foreign key across a module boundary.
    /// </summary>
    public int PartyId{get;set;}public string PartyName{get;set;}="";public string? SourceReference{get;set;}public string Reason{get;set;}="";public string? Notes{get;set;}public string PostedByName{get;set;}="";public List<InventoryReturnLine> Lines{get;set;}=[];public decimal Total=>Lines.Sum(x=>x.Quantity*x.UnitCost);
}
public class InventoryReturnLine:Entity
{
    public int InventoryReturnId{get;set;}public InventoryReturn? Return{get;set;}public int ItemId{get;set;}public Item? Item{get;set;}public string ItemCode{get;set;}="";public string ItemName{get;set;}="";public decimal Quantity{get;set;}public decimal UnitCost{get;set;}public string? SerialNumbers{get;set;}public string? BatchNumber{get;set;}
}
public sealed record ReturnLineInput(int ItemId,decimal Quantity,string? SerialNumbers=null,string? BatchNumber=null);
public sealed record ReturnInput(InventoryReturnKind Kind,int PartyId,string PartyName,DateOnly Date,string? SourceReference,string Reason,string? Notes,IReadOnlyList<ReturnLineInput> Lines);
public interface IInventoryReturnService{Task<List<InventoryReturn>> ListAsync(InventoryReturnKind? kind=null,CancellationToken ct=default);Task<InventoryReturn?> GetAsync(int id,CancellationToken ct=default);Task<Result<InventoryReturn>> PostAsync(ReturnInput input,CancellationToken ct=default);}
public sealed class InventoryReturnService(InventoryDbContext db,IStockService stock,IClock clock,ICurrentUser user):IInventoryReturnService
{
    public Task<List<InventoryReturn>> ListAsync(InventoryReturnKind? kind=null,CancellationToken ct=default)=>db.InventoryReturns.AsNoTracking().Include(x=>x.Lines).Where(x=>kind==null||x.Kind==kind).OrderByDescending(x=>x.Id).ToListAsync(ct);
    public Task<InventoryReturn?> GetAsync(int id,CancellationToken ct=default)=>db.InventoryReturns.AsNoTracking().Include(x=>x.Lines).FirstOrDefaultAsync(x=>x.Id==id,ct);
    public async Task<Result<InventoryReturn>> PostAsync(ReturnInput input,CancellationToken ct=default)
    {
        if(string.IsNullOrWhiteSpace(input.Reason))return Result.Fail<InventoryReturn>("A return reason is required.","return.no-reason");if(input.Lines.Count==0||input.Lines.Any(x=>x.Quantity<=0))return Result.Fail<InventoryReturn>("Add at least one positive return line.","return.no-lines");if(input.PartyId<=0||string.IsNullOrWhiteSpace(input.PartyName))return Result.Fail<InventoryReturn>("Choose a party for this return.","return.no-party");var items=await db.Items.Where(x=>input.Lines.Select(l=>l.ItemId).Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct);if(items.Count!=input.Lines.Select(x=>x.ItemId).Distinct().Count())return Result.Fail<InventoryReturn>("Item not found.");
        foreach(var line in input.Lines){var item=items[line.ItemId];var serials=Split(line.SerialNumbers);if(item.IsSerialized){if(line.Quantity!=decimal.Truncate(line.Quantity)||serials.Count!=(int)line.Quantity)return Result.Fail<InventoryReturn>($"Enter exactly {line.Quantity:0} serial numbers for {item.Name}.","return.serial-count");var units=await db.StockUnits.Where(x=>x.ItemId==item.Id&&serials.Contains(x.SerialNumber)).ToListAsync(ct);if(units.Count!=serials.Count)return Result.Fail<InventoryReturn>("A serial number is not recorded.","return.bad-serial");var wanted=input.Kind==InventoryReturnKind.SalesReturn?StockUnitStatus.Sold:StockUnitStatus.InStock;if(units.Any(x=>x.Status!=wanted))return Result.Fail<InventoryReturn>("A serial is not in the status required for this return.","return.serial-status");}else if(serials.Count>0)return Result.Fail<InventoryReturn>("This item is not serialized.");if(input.Kind==InventoryReturnKind.PurchaseReturn&&item.QuantityOnHand<line.Quantity)return Result.Fail<InventoryReturn>($"Only {item.QuantityOnHand:0.##} of {item.Name} is in stock.","return.insufficient");if(item.IsBatchTracked&&input.Kind==InventoryReturnKind.SalesReturn&&!await db.StockBatches.AnyAsync(x=>x.ItemId==item.Id&&x.BatchNumber==line.BatchNumber,ct))return Result.Fail<InventoryReturn>("Choose the original batch for a batch-tracked sales return.","return.batch-required");if(item.IsBatchTracked&&input.Kind==InventoryReturnKind.PurchaseReturn&&await db.StockBatches.Where(x=>x.ItemId==item.Id).SumAsync(x=>x.RemainingQuantity,ct)<line.Quantity)return Result.Fail<InventoryReturn>("Tracked batches do not contain enough stock.","return.batch-insufficient");}
        var row=new InventoryReturn{Number=$"{(input.Kind==InventoryReturnKind.SalesReturn?"SR":"PR")}-{clock.Today.Year}-{await db.InventoryReturns.CountAsync(ct)+1:D5}",Date=input.Date,Kind=input.Kind,PartyId=input.PartyId,PartyName=input.PartyName.Trim(),SourceReference=input.SourceReference,Reason=input.Reason.Trim(),Notes=input.Notes,PostedByName=user.Name??"Unknown"};db.Add(row);
        foreach(var line in input.Lines){var item=items[line.ItemId];var serials=Split(line.SerialNumbers);if(input.Kind==InventoryReturnKind.SalesReturn){var moved=await stock.StageReceiptAsync(item.Id,line.Quantity,item.AverageCost,input.Date,StockMovementType.SalesReturn,row.Number,"inventory-return",null,ct);if(moved.Failed){db.ChangeTracker.Clear();return Result.Fail<InventoryReturn>(moved.Error!,moved.Code);}foreach(var unit in await db.StockUnits.Where(x=>x.ItemId==item.Id&&serials.Contains(x.SerialNumber)).ToListAsync(ct)){unit.Status=StockUnitStatus.Returned;unit.IssuedOn=null;unit.IssuedTo=null;unit.Reference=row.Number;}if(item.IsBatchTracked){var batch=await db.StockBatches.FirstOrDefaultAsync(x=>x.ItemId==item.Id&&x.BatchNumber==line.BatchNumber,ct);if(batch is null)return Result.Fail<InventoryReturn>("Choose the original batch for a batch-tracked sales return.","return.batch-required");batch.RemainingQuantity+=line.Quantity;}}
            else{var moved=await stock.StageIssueAsync(item.Id,line.Quantity,input.Date,StockMovementType.PurchaseReturn,row.Number,"inventory-return",null,ct);if(moved.Failed){db.ChangeTracker.Clear();return Result.Fail<InventoryReturn>(moved.Error!,moved.Code);}foreach(var unit in await db.StockUnits.Where(x=>x.ItemId==item.Id&&serials.Contains(x.SerialNumber)).ToListAsync(ct)){unit.Status=StockUnitStatus.Scrapped;unit.IssuedOn=input.Date;unit.IssuedTo=input.PartyName;unit.Reference=row.Number;}if(item.IsBatchTracked){var left=line.Quantity;var batches=await db.StockBatches.Where(x=>x.ItemId==item.Id&&x.RemainingQuantity>0).OrderBy(x=>x.ExpiresOn??DateOnly.MaxValue).ToListAsync(ct);if(batches.Sum(x=>x.RemainingQuantity)<left)return Result.Fail<InventoryReturn>("Tracked batches do not contain enough stock.");foreach(var batch in batches){var q=Math.Min(left,batch.RemainingQuantity);batch.RemainingQuantity-=q;left-=q;if(left==0)break;}}}row.Lines.Add(new(){ItemId=item.Id,ItemCode=item.Code,ItemName=item.Name,Quantity=line.Quantity,UnitCost=item.AverageCost,SerialNumbers=line.SerialNumbers,BatchNumber=line.BatchNumber});}
        try{await db.SaveChangesAsync(ct);return Result.Success(row);}catch{db.ChangeTracker.Clear();throw;}
    }
    private static List<string> Split(string? raw)=>(raw??"").Split([',','\n','\r'],StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).ToList();
}
