using MeiErp.Platform.Reporting;using Microsoft.Extensions.DependencyInjection;
namespace MeiErp.Modules.Ledger;
public static class LedgerReports
{
 public static IServiceCollection AddLedgerReports(this IServiceCollection s){s.AddSingleton<ReportDefinition>(sp=>Outstanding(sp));s.AddSingleton<ReportDefinition>(sp=>Tree(sp));s.AddSingleton<ReportDefinition>(sp=>Heads(sp));return s;}
 private static ReportDefinition Base(IServiceProvider sp,string key,string name,string description,Func<IServiceProvider,CancellationToken,Task<ReportResult>> run)=>new(){Key="ledger."+key,Name=name,Description=description,ModuleKey=LedgerModule.Key,Group="Balances",Permission=LedgerPermissions.ReportsView,Uses=ReportFilters.None,Run=async(r,ct)=>{using var scope=sp.CreateScope();return await run(scope.ServiceProvider,ct);}};
 private static ReportDefinition Outstanding(IServiceProvider sp)=>Base(sp,"outstanding","Outstanding Ledgers","Open ledgers still carrying a balance.",async(p,ct)=>{var rows=(await p.GetRequiredService<ILedgerService>().ListAsync(new(OutstandingOnly:true),ct)).Where(x=>x.Status==LedgerStatus.Open).Select(x=>new{Ledger=x,Balance=x.OpeningBalance+x.Entries.Sum(e=>e.SignedAmount)}).Where(x=>x.Balance!=0).OrderByDescending(x=>Math.Abs(x.Balance)).ToList();return new(){Columns=[new("ledger","Ledger"),new("counterparty","Counterparty"),new("nature","Type",ReportValueKind.Status),new("entries","Entries",ReportValueKind.Number),new("balance","Balance",ReportValueKind.Money)],Rows=[..rows.Select(x=>new ReportRow(new Dictionary<string,object?>{{"ledger",x.Ledger.Name},{"counterparty",x.Ledger.CounterpartyName},{"nature",x.Ledger.Nature},{"entries",x.Ledger.Entries.Count},{"balance",x.Balance}},$"/ledger/ledgers/{x.Ledger.Id}"))],Totals=[new("balance",rows.Sum(x=>x.Balance))]};});
 private static ReportDefinition Tree(IServiceProvider sp)=>Base(sp,"tree-rollup","Ledger Tree Rollup","Main-ledger own and descendant balances.",async(p,ct)=>{var rows=await p.GetRequiredService<ILedgerService>().GetTreeAsync(ct:ct);return new(){Columns=[new("ledger","Main ledger"),new("counterparty","Counterparty"),new("children","Sub-ledgers",ReportValueKind.Number),new("own","Unallocated",ReportValueKind.Money),new("rollup","Whole tree",ReportValueKind.Money)],Rows=[..rows.Select(x=>new ReportRow(new Dictionary<string,object?>{{"ledger",x.Ledger.Name},{"counterparty",x.Ledger.CounterpartyName},{"children",Count(x)},{"own",x.Balance.Own},{"rollup",x.Balance.Rollup}},$"/ledger/ledgers/{x.Ledger.Id}"))],Totals=[new("own",rows.Sum(x=>x.Balance.Own)),new("rollup",rows.Sum(x=>x.Balance.Rollup))]};});
 private static ReportDefinition Heads(IServiceProvider sp)=>Base(sp,"by-head","Ledger Activity by Head","Own and sub-head inflows and outflows.",async(p,ct)=>{var svc=p.GetRequiredService<ILedgerHeadService>();var heads=await svc.ListAsync(ct:ct);var totals=await svc.GetTotalsAsync(ct);return new(){Columns=[new("head","Head"),new("ledgers","Ledgers",ReportValueKind.Number),new("entries","Entries",ReportValueKind.Number),new("ownIn","Own in",ReportValueKind.Money),new("ownOut","Own out",ReportValueKind.Money),new("rollupIn","In with sub-heads",ReportValueKind.Money),new("rollupOut","Out with sub-heads",ReportValueKind.Money),new("net","Net",ReportValueKind.Money)],Rows=[..heads.Select(x=>{var t=totals.GetValueOrDefault(x.Id);return new ReportRow(new Dictionary<string,object?>{{"head",x.Name},{"ledgers",t?.LedgerCount??0},{"entries",t?.OwnEntryCount??0},{"ownIn",t?.OwnIn??0},{"ownOut",t?.OwnOut??0},{"rollupIn",t?.RollupIn??0},{"rollupOut",t?.RollupOut??0},{"net",(t?.RollupIn??0)-(t?.RollupOut??0)}});})]};});
 private static int Count(LedgerNode n)=>n.Children.Count+n.Children.Sum(Count);
}
