using System.Text.Json;
using MySqlConnector;
using Npgsql;

namespace MeiErp.LegacyImport;

internal static class IdentityImporter
{
    private static readonly JsonSerializerOptions Json=new(){WriteIndented=true};
    public static async Task<int> RunAsync(ImportOptions o,string password)
    {
        await using var source=new MySqlConnection($"Server={o.MySqlHost};Port={o.MySqlPort};Database=erp_identity;User ID={o.MySqlUser};Password={password};SslMode=Preferred");await source.OpenAsync();
        var tables=await Read(source);var errors=Validate(tables);
        Console.WriteLine(JsonSerializer.Serialize(new {Module="identity",o.Apply,Users=tables.Users,Roles=tables.Roles,RoleClaims=tables.RoleClaims,UserClaims=tables.UserClaims,UserLogins=tables.UserLogins,UserRoles=tables.UserRoles,UserTokens=tables.UserTokens,ModuleAccess=tables.ModuleAccess,Companies=tables.Companies,Rejections=errors},Json));
        if(errors.Count>0){Console.Error.WriteLine("Validation rejected source rows; nothing was written.");return 2;}if(!o.Apply)return 0;
        var pg=Environment.GetEnvironmentVariable("MEIERP_DB_PASSWORD");if(string.IsNullOrEmpty(pg)){Console.Error.WriteLine("Set MEIERP_DB_PASSWORD for an apply run.");return 2;}
        await using var target=new NpgsqlConnection($"Host={o.PgHost};Port={o.PgPort};Database={o.PgDatabase};Username={o.PgUser};Password={pg}");await target.OpenAsync();await Apply(target,tables);Console.WriteLine("Identity import committed and target counts reconciled.");return 0;
    }

    private sealed record Data(List<Dictionary<string,object?>> Users,List<Dictionary<string,object?>> Roles,List<Dictionary<string,object?>> RoleClaims,List<Dictionary<string,object?>> UserClaims,List<Dictionary<string,object?>> UserLogins,List<Dictionary<string,object?>> UserRoles,List<Dictionary<string,object?>> UserTokens,List<Dictionary<string,object?>> ModuleAccess,List<Dictionary<string,object?>> Companies);
    private static async Task<Data> Read(MySqlConnection db)=>new(await Rows(db,"AspNetUsers"),await Rows(db,"AspNetRoles"),await Rows(db,"AspNetRoleClaims"),await Rows(db,"AspNetUserClaims"),await Rows(db,"AspNetUserLogins"),await Rows(db,"AspNetUserRoles"),await Rows(db,"AspNetUserTokens"),await Rows(db,"UserModuleAccess"),await Rows(db,"CompanyProfiles"));
    private static async Task<List<Dictionary<string,object?>>> Rows(MySqlConnection db,string table){await using var c=new MySqlCommand($"SELECT * FROM `{table}`",db);await using var r=await c.ExecuteReaderAsync();var rows=new List<Dictionary<string,object?>>();while(await r.ReadAsync()){var row=new Dictionary<string,object?>(StringComparer.OrdinalIgnoreCase);for(var i=0;i<r.FieldCount;i++)row[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);rows.Add(row);}return rows;}
    private static List<string> Validate(Data d){var e=new List<string>();var users=d.Users.Select(x=>String(x,"Id")).ToHashSet();var roles=d.Roles.Select(x=>String(x,"Id")).ToHashSet();foreach(var x in d.Users){if(string.IsNullOrWhiteSpace(String(x,"Id"))||string.IsNullOrWhiteSpace(String(x,"FullName")))e.Add("A user is missing Id or FullName.");var manager=String(x,"ManagerId");if(!string.IsNullOrWhiteSpace(manager)&&!users.Contains(manager))e.Add($"User {String(x,"Id")} references missing manager {manager}.");}foreach(var x in d.Roles)if(string.IsNullOrWhiteSpace(String(x,"Id")))e.Add("A role is missing Id.");foreach(var x in d.RoleClaims)if(!roles.Contains(String(x,"RoleId")))e.Add($"Role claim references missing role {String(x,"RoleId")}. ");foreach(var x in d.UserClaims)if(!users.Contains(String(x,"UserId")))e.Add($"User claim references missing user {String(x,"UserId")}. ");foreach(var x in d.UserRoles){if(!users.Contains(String(x,"UserId")))e.Add($"User role references missing user {String(x,"UserId")}. ");if(!roles.Contains(String(x,"RoleId")))e.Add($"User role references missing role {String(x,"RoleId")}. ");}foreach(var x in d.ModuleAccess)if(!users.Contains(String(x,"UserId")))e.Add($"Module access references missing user {String(x,"UserId")}. ");return e.Distinct().ToList();}
    private static async Task Apply(NpgsqlConnection db,Data d){await using var tx=await db.BeginTransactionAsync();await using(var guard=new NpgsqlCommand("SELECT (SELECT COUNT(*) FROM platform.\"AspNetUsers\")+(SELECT COUNT(*) FROM platform.\"AspNetRoles\")+(SELECT COUNT(*) FROM platform.\"CompanyProfiles\")",db,tx))if(Convert.ToInt64(await guard.ExecuteScalarAsync())!=0)throw new InvalidOperationException("Identity target is not empty.");foreach(var r in d.Roles)await Insert(db,tx,"platform.\"AspNetRoles\"",r,"IsSystemRole","IsSystem");foreach(var u in d.Users)await Insert(db,tx,"platform.\"AspNetUsers\"",u,"LineManagerId",null,"DepartmentId",null,"CreatedUtc",DateTime.UtcNow,"MustChangePassword",false);foreach(var u in d.Users.Where(x=>!string.IsNullOrWhiteSpace(String(x,"ManagerId"))))await Exec(db,tx,"UPDATE platform.\"AspNetUsers\" SET \"LineManagerId\"=@manager WHERE \"Id\"=@id",("manager",String(u,"ManagerId")),("id",String(u,"Id")));foreach(var c in d.RoleClaims)await Insert(db,tx,"platform.\"AspNetRoleClaims\"",c);foreach(var c in d.UserClaims)await Insert(db,tx,"platform.\"AspNetUserClaims\"",c);foreach(var x in d.UserLogins)await Insert(db,tx,"platform.\"AspNetUserLogins\"",x);foreach(var x in d.UserRoles)await Insert(db,tx,"platform.\"AspNetUserRoles\"",x);foreach(var x in d.UserTokens)await Insert(db,tx,"platform.\"AspNetUserTokens\"",x);foreach(var x in d.ModuleAccess)await Insert(db,tx,"platform.\"ModuleAccess\"",x,"Granted","IsGranted","Reason",null,"SetUtc",DateTime.UtcNow,"SetBy",null);foreach(var x in d.Companies)await Insert(db,tx,"platform.\"CompanyProfiles\"",x);await using(var check=new NpgsqlCommand("SELECT (SELECT COUNT(*) FROM platform.\"AspNetUsers\"),(SELECT COUNT(*) FROM platform.\"AspNetRoles\"),(SELECT COUNT(*) FROM platform.\"AspNetRoleClaims\"),(SELECT COUNT(*) FROM platform.\"AspNetUserClaims\"),(SELECT COUNT(*) FROM platform.\"AspNetUserLogins\"),(SELECT COUNT(*) FROM platform.\"AspNetUserRoles\"),(SELECT COUNT(*) FROM platform.\"AspNetUserTokens\"),(SELECT COUNT(*) FROM platform.\"ModuleAccess\"),(SELECT COUNT(*) FROM platform.\"CompanyProfiles\")",db,tx))await using(var r=await check.ExecuteReaderAsync()){await r.ReadAsync();var expected=new[]{d.Users.Count,d.Roles.Count,d.RoleClaims.Count,d.UserClaims.Count,d.UserLogins.Count,d.UserRoles.Count,d.UserTokens.Count,d.ModuleAccess.Count,d.Companies.Count};for(var i=0;i<expected.Length;i++)if(r.GetInt64(i)!=expected[i])throw new InvalidOperationException("Identity count reconciliation failed.");}await tx.CommitAsync();}
    private static async Task Exec(NpgsqlConnection db,NpgsqlTransaction tx,string sql,params (string,object?)[] p){await using var c=new NpgsqlCommand(sql,db,tx);foreach(var x in p)c.Parameters.AddWithValue(x.Item1,x.Item2??DBNull.Value);await c.ExecuteNonQueryAsync();}
    private static async Task Insert(NpgsqlConnection db,NpgsqlTransaction tx,string table,Dictionary<string,object?> source,params object?[] aliases){var map=new Dictionary<string,object?>(source,StringComparer.OrdinalIgnoreCase);for(var i=0;i+1<aliases.Length;i+=2){var target=(string)aliases[i]!;var old=aliases[i+1];map[target]=old is string s?Value(source,s):old;}var excluded=new HashSet<string>(StringComparer.OrdinalIgnoreCase){"ManagerId","IsSystem","IsGranted","CreatedAtUtc","CreatedBy","Reason","SetBy","Tagline","LogoContentType","LogoFileName"};var columns=map.Keys.Where(k=>!excluded.Contains(k)).ToList();var names=columns.Select(x=>$"\"{x}\"");var parms=columns.Select((x,i)=>$"@p{i}");await using var c=new NpgsqlCommand($"INSERT INTO {table} ({string.Join(',',names)}) VALUES ({string.Join(',',parms)})",db,tx);for(var i=0;i<columns.Count;i++)c.Parameters.AddWithValue($"p{i}",map[columns[i]]??DBNull.Value);await c.ExecuteNonQueryAsync();}
    private static object? Value(Dictionary<string,object?> d,string key)=>d.TryGetValue(key,out var value)?value:null;private static string String(Dictionary<string,object?> d,string key)=>Convert.ToString(Value(d,key))??"";
}
