using System.Data.Common;
using System.Text.Json;
using MySqlConnector;
using Npgsql;

namespace MeiErp.LegacyImport;

internal static class TenderImporter
{
    private static readonly JsonSerializerOptions Json = new() { WriteIndented = true };

    public static async Task<int> RunAsync(ImportOptions o, string password)
    {
        await using var source = new MySqlConnection($"Server={o.MySqlHost};Port={o.MySqlPort};Database=erp_tender;User ID={o.MySqlUser};Password={password};SslMode=Preferred");
        await source.OpenAsync();
        var tenders = await ReadTenders(source);
        var guarantees = await ReadGuarantees(source);
        var documents = await ReadDocuments(source);
        var competitors = await ReadCompetitors(source);
        var items = await ReadItems(source);
        var projects = await ReadProjects(source);
        var tasks = await ReadTasks(source);
        var milestones = await ReadMilestones(source);
        var rejects = Validate(tenders, guarantees, documents, competitors, items, projects, tasks, milestones);
        Console.WriteLine(JsonSerializer.Serialize(new { Module = "tender", o.Apply, Tenders = tenders.Count, Guarantees = guarantees.Count, Documents = documents.Count, Competitors = competitors.Count, Items = items.Count, Projects = projects.Count, Tasks = tasks.Count, Milestones = milestones.Count, Rejections = rejects }, Json));
        if (rejects.Count > 0) return Fail("Validation rejected source rows; nothing was written.");
        if (!o.Apply) return 0;
        var pgPassword = Environment.GetEnvironmentVariable("MEIERP_DB_PASSWORD");
        if (string.IsNullOrEmpty(pgPassword)) return Fail("Set MEIERP_DB_PASSWORD for an apply run.");
        await using var target = new NpgsqlConnection($"Host={o.PgHost};Port={o.PgPort};Database={o.PgDatabase};Username={o.PgUser};Password={pgPassword}");
        await target.OpenAsync();
        await Apply(target, tenders, guarantees, documents, competitors, items, projects, tasks, milestones);
        Console.WriteLine("Tender import committed and target counts reconciled.");
        return 0;
    }

    private static async Task<List<TenderRow>> ReadTenders(MySqlConnection db) =>
        await Read(db, "SELECT * FROM Tenders ORDER BY Id", r => new TenderRow(
            I(r, "Id"), S(r, "TenderNumber") ?? "", S(r, "Title") ?? "", S(r, "IssuingAuthority") ?? "", S(r, "Department"), S(r, "Description"),
            D(r, "EstimatedValue"), ND(r, "TenderFee"), ND(r, "EmdAmount"), B(r, "IsEmdExempted"), S(r, "EmdExemptionReason"), ND(r, "PerformanceGuaranteePercentage"), ND(r, "RetentionMoneyPercentage"),
            I(r, "SubmissionMode"), S(r, "PortalReference"), NI(r, "BidValidityDays"), Date(r, "PublishDate"), Date(r, "SubmissionDeadline"), Date(r, "TechnicalOpeningDate"), Date(r, "FinancialOpeningDate"),
            I(r, "Status"), NI(r, "OurRank"), ND(r, "L1Amount"), ND(r, "AwardedValue"), Date(r, "AwardDate"), S(r, "WorkOrderNumber"), Date(r, "ContractStartDate"), Date(r, "ContractEndDate"), NI(r, "CompletionPeriodDays"), NI(r, "DefectLiabilityPeriodMonths"), S(r, "PaymentTerms"), S(r, "ContactPerson"), S(r, "ContactPhone"), S(r, "ContactEmail"), S(r, "Notes"), Audit(r)));

    private static async Task<List<GuaranteeRow>> ReadGuarantees(MySqlConnection db) =>
        await Read(db, "SELECT * FROM Guarantees ORDER BY Id", r => new GuaranteeRow(I(r, "Id"), I(r, "TenderRecordId"), I(r, "Type"), I(r, "InstrumentType"), S(r, "BankName"), S(r, "BranchName"), S(r, "BankContactPerson"), S(r, "BankContactPhone"), S(r, "GuaranteeNumber"), D(r, "Amount"), Date(r, "IssueDate"), Date(r, "ExpiryDate"), Date(r, "ClaimPeriodEndDate"), I(r, "Status"), Date(r, "ReleaseDate"), S(r, "ReleaseReference"), S(r, "Remarks"), ND(r, "Charges"), NI(r, "RenewalOfGuaranteeId"), Audit(r)));

    private static async Task<List<DocumentRow>> ReadDocuments(MySqlConnection db) =>
        await Read(db, "SELECT * FROM Documents ORDER BY Id", r => new DocumentRow(I(r, "Id"), I(r, "TenderRecordId"), I(r, "Category"), S(r, "Name") ?? "", S(r, "ReferenceNumber"), Date(r, "DocumentDate"), S(r, "Notes"), Audit(r)));

    private static async Task<List<CompetitorRow>> ReadCompetitors(MySqlConnection db) =>
        await Read(db, "SELECT * FROM Competitors ORDER BY Id", r => new CompetitorRow(I(r, "Id"), I(r, "TenderRecordId"), S(r, "BidderName") ?? "", D(r, "QuotedAmount"), NI(r, "Rank"), B(r, "IsOwnBid"), S(r, "Remarks"), Audit(r)));

    private static async Task<List<ItemRow>> ReadItems(MySqlConnection db) =>
        await Read(db, "SELECT * FROM TenderItems ORDER BY Id", r => new ItemRow(I(r, "Id"), I(r, "TenderRecordId"), S(r, "ItemCode"), S(r, "Description") ?? "", S(r, "Specification"), S(r, "Unit"), D(r, "Quantity"), D(r, "UnitRate"), D(r, "EstimatedRate"), D(r, "CostRate"), S(r, "Brand"), S(r, "CountryOfOrigin"), NI(r, "DeliveryDays"), I(r, "SortOrder"), S(r, "Remarks"), Audit(r)));

    private static async Task<List<ProjectRow>> ReadProjects(MySqlConnection db) =>
        await Read(db, "SELECT * FROM Projects ORDER BY Id", r => new ProjectRow(I(r, "Id"), S(r, "ProjectCode") ?? "", S(r, "Name") ?? "", S(r, "Client"), S(r, "Description"), S(r, "Location"), S(r, "ManagerUserId"), S(r, "ManagerName"), ND(r, "ContractValue"), ND(r, "Budget"), Date(r, "StartDate"), Date(r, "TargetEndDate"), Date(r, "ActualEndDate"), I(r, "Status"), I(r, "Priority"), S(r, "ContactPerson"), S(r, "ContactPhone"), S(r, "ContactEmail"), S(r, "Notes"), Audit(r)));

    private static async Task<List<TaskRow>> ReadTasks(MySqlConnection db) =>
        await Read(db, "SELECT * FROM WorkTasks ORDER BY Id", r => new TaskRow(I(r, "Id"), NI(r, "ProjectId"), NI(r, "TenderRecordId"), S(r, "Title") ?? "", S(r, "Description"), S(r, "AssignedToUserId"), S(r, "AssignedToName"), Date(r, "StartDate"), Date(r, "DueDate"), Date(r, "CompletedDate"), I(r, "Status"), I(r, "Priority"), I(r, "ProgressPercent"), ND(r, "EstimatedHours"), ND(r, "ActualHours"), I(r, "SortOrder"), S(r, "Notes"), Audit(r)));

    private static async Task<List<MilestoneRow>> ReadMilestones(MySqlConnection db) =>
        await Read(db, "SELECT * FROM ProjectMilestones ORDER BY Id", r => new MilestoneRow(I(r, "Id"), I(r, "ProjectId"), S(r, "Name") ?? "", S(r, "Description"), Date(r, "DueDate"), Date(r, "AchievedDate"), I(r, "Status"), ND(r, "PaymentAmount"), I(r, "SortOrder"), S(r, "Notes"), Audit(r)));

    private static async Task<List<T>> Read<T>(MySqlConnection db, string sql, Func<DbDataReader, T> map)
    {
        await using var command = new MySqlCommand(sql, db);
        await using var reader = await command.ExecuteReaderAsync();
        var rows = new List<T>();
        while (await reader.ReadAsync()) rows.Add(map(reader));
        return rows;
    }

    private static List<string> Validate(List<TenderRow> t, List<GuaranteeRow> g, List<DocumentRow> d, List<CompetitorRow> c, List<ItemRow> i, List<ProjectRow> p, List<TaskRow> tasks, List<MilestoneRow> milestones)
    {
        var errors = new List<string>(); var ids = t.Select(x => x.Id).ToHashSet();
        foreach (var row in t) try { _ = TenderMapping.Status(row.Status); _ = TenderMapping.Bounded(row.Submission, 0, 2, "submission mode"); _ = TenderMapping.NonNegative(row.Estimate, $"tender {row.Id} estimate"); } catch (Exception e) { errors.Add(e.Message); }
        var guaranteeIds = g.Select(x => x.Id).ToHashSet();
        foreach (var row in g) try { if (!ids.Contains(row.TenderId)) errors.Add($"Guarantee {row.Id} references missing tender {row.TenderId}."); if (row.RenewalOfGuaranteeId is { } renewal && !guaranteeIds.Contains(renewal)) errors.Add($"Guarantee {row.Id} references missing renewal {renewal}."); _ = TenderMapping.GuaranteeKind(row.Type); _ = TenderMapping.Bounded(row.InstrumentType, 0, 5, "guarantee instrument"); _ = TenderMapping.Bounded(row.Status, 0, 4, "guarantee status"); _ = TenderMapping.NonNegative(row.Amount, $"guarantee {row.Id} amount"); } catch (Exception e) { errors.Add(e.Message); }
        foreach (var row in d) { if (!ids.Contains(row.TenderId)) errors.Add($"Document {row.Id} references missing tender {row.TenderId}."); try { _ = TenderMapping.Bounded(row.Category, 0, 8, "document category"); } catch (Exception e) { errors.Add(e.Message); } if (string.IsNullOrWhiteSpace(row.Name)) errors.Add($"Document {row.Id} has no name."); }
        foreach (var row in c) { if (!ids.Contains(row.TenderId)) errors.Add($"Competitor {row.Id} references missing tender {row.TenderId}."); if (string.IsNullOrWhiteSpace(row.Name)) errors.Add($"Competitor {row.Id} has no bidder name."); try { _ = TenderMapping.NonNegative(row.Amount, $"competitor {row.Id} amount"); } catch (Exception e) { errors.Add(e.Message); } if (row.Rank is < 1) errors.Add($"Competitor {row.Id} has an invalid rank."); }
        foreach (var row in i) { if (!ids.Contains(row.TenderId)) errors.Add($"Item {row.Id} references missing tender {row.TenderId}."); if (string.IsNullOrWhiteSpace(row.Description)) errors.Add($"Item {row.Id} has no description."); try { _ = TenderMapping.NonNegative(row.Quantity, $"item {row.Id} quantity"); _ = TenderMapping.NonNegative(row.Rate, $"item {row.Id} rate"); } catch (Exception e) { errors.Add(e.Message); } }
        var projectIds = p.Select(x => x.Id).ToHashSet();
        foreach (var row in p) { if (string.IsNullOrWhiteSpace(row.Code) || string.IsNullOrWhiteSpace(row.Name)) errors.Add($"Project {row.Id} is missing code or name."); try { _ = TenderMapping.Bounded(row.Status, 0, 4, "project status"); } catch (Exception e) { errors.Add(e.Message); } }
        foreach (var row in tasks) { if (row.ProjectId is null == (row.TenderId is null)) errors.Add($"Task {row.Id} must belong to exactly one project or tender."); if (row.ProjectId is { } projectId && !projectIds.Contains(projectId)) errors.Add($"Task {row.Id} references missing project {projectId}."); if (row.TenderId is { } tenderId && !ids.Contains(tenderId)) errors.Add($"Task {row.Id} references missing tender {tenderId}."); if (string.IsNullOrWhiteSpace(row.Title)) errors.Add($"Task {row.Id} has no title."); try { _ = TenderMapping.Bounded(row.Status, 0, 3, "work task status"); _ = TenderMapping.NonNegative(row.Progress, $"task {row.Id} progress"); } catch (Exception e) { errors.Add(e.Message); } if (row.Progress > 100) errors.Add($"Task {row.Id} progress exceeds 100."); }
        foreach (var row in milestones) { if (!projectIds.Contains(row.ProjectId)) errors.Add($"Milestone {row.Id} references missing project {row.ProjectId}."); if (string.IsNullOrWhiteSpace(row.Name)) errors.Add($"Milestone {row.Id} has no name."); try { _ = TenderMapping.Bounded(row.Status, 0, 3, "milestone status"); } catch (Exception e) { errors.Add(e.Message); } }
        return errors;
    }

    private static async Task Apply(NpgsqlConnection db, List<TenderRow> t, List<GuaranteeRow> g, List<DocumentRow> d, List<CompetitorRow> c, List<ItemRow> i, List<ProjectRow> p, List<TaskRow> tasks, List<MilestoneRow> milestones)
    {
        await using var tx = await db.BeginTransactionAsync();
        await using (var count = new NpgsqlCommand("SELECT (SELECT COUNT(*) FROM tender.\"Tenders\")+(SELECT COUNT(*) FROM tender.\"Guarantees\")+(SELECT COUNT(*) FROM tender.\"Documents\")+(SELECT COUNT(*) FROM tender.\"Competitors\")+(SELECT COUNT(*) FROM tender.\"TenderItems\")+(SELECT COUNT(*) FROM tender.\"Projects\")+(SELECT COUNT(*) FROM tender.\"ProjectTasks\")+(SELECT COUNT(*) FROM tender.\"TenderTasks\")+(SELECT COUNT(*) FROM tender.\"ProjectMilestones\")", db, tx))
            if (Convert.ToInt64(await count.ExecuteScalarAsync()) != 0) throw new InvalidOperationException("Tender target is not empty.");
        foreach (var x in t) await Exec(db, tx, "INSERT INTO tender.\"Tenders\" (\"Id\",\"Reference\",\"Title\",\"ClientName\",\"IssuingAuthority\",\"Department\",\"Description\",\"PublishedOn\",\"SubmissionDeadline\",\"TechnicalOpeningDate\",\"FinancialOpeningDate\",\"EstimatedValue\",\"TenderFee\",\"EmdAmount\",\"IsEmdExempted\",\"EmdExemptionReason\",\"PerformanceGuaranteePercentage\",\"RetentionMoneyPercentage\",\"SubmissionMode\",\"PortalReference\",\"BidValidityDays\",\"Status\",\"OurRank\",\"L1Amount\",\"AwardedValue\",\"AwardDate\",\"WorkOrderNumber\",\"ContractStartDate\",\"ContractEndDate\",\"CompletionPeriodDays\",\"DefectLiabilityPeriodMonths\",\"PaymentTerms\",\"ContactPerson\",\"ContactPhone\",\"ContactEmail\",\"Notes\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@reference,@title,@client,@authority,@department,@description,@published,@deadline,@technical,@financial,@estimate,@fee,@emd,@exempt,@reason,@performance,@retention,@submission,@portal,@validity,@status,@rank,@l1,@awarded,@award,@workOrder,@contractStart,@contractEnd,@completion,@defect,@terms,@contact,@phone,@email,@notes,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("reference", x.Number), ("title", x.Title), ("client", (object?)null), ("authority", x.Authority), ("department", x.Department), ("description", x.Description), ("published", x.Publish), ("deadline", x.Deadline), ("technical", x.Technical), ("financial", x.Financial), ("estimate", x.Estimate), ("fee", x.Fee), ("emd", x.Emd), ("exempt", x.Exempt), ("reason", x.ExemptReason), ("performance", x.Performance), ("retention", x.Retention), ("submission", x.Submission), ("portal", x.Portal), ("validity", x.Validity), ("status", TenderMapping.Status(x.Status)), ("rank", x.Rank), ("l1", x.L1), ("awarded", x.Awarded), ("award", x.AwardDate), ("workOrder", x.WorkOrder), ("contractStart", x.ContractStart), ("contractEnd", x.ContractEnd), ("completion", x.Completion), ("defect", x.Defect), ("terms", x.Terms), ("contact", x.ContactPerson), ("phone", x.ContactPhone), ("email", x.ContactEmail), ("notes", x.Notes), AuditArgs(x.Audit));
        foreach (var x in g) await Exec(db, tx, "INSERT INTO tender.\"Guarantees\" (\"Id\",\"TenderRecordId\",\"Kind\",\"InstrumentType\",\"Status\",\"InstrumentNumber\",\"BankName\",\"BranchName\",\"BankContactPerson\",\"BankContactPhone\",\"Amount\",\"IssuedOn\",\"ExpiresOn\",\"Charges\",\"ClaimPeriodEndDate\",\"ReleasedOn\",\"ReleaseReference\",\"Remarks\",\"RenewalOfGuaranteeId\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@tender,@kind,@instrument,@status,@number,@bank,@branch,@bankContact,@bankPhone,@amount,@issued,@expires,@charges,@claim,@released,@releaseRef,@remarks,NULL,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("tender", x.TenderId), ("kind", TenderMapping.GuaranteeKind(x.Type)), ("instrument", x.InstrumentType), ("status", x.Status), ("number", x.Number), ("bank", x.Bank), ("branch", x.Branch), ("bankContact", x.BankContactPerson), ("bankPhone", x.BankContactPhone), ("amount", x.Amount), ("issued", x.Issue), ("expires", x.Expiry), ("charges", x.Charges), ("claim", x.Claim), ("released", x.Release), ("releaseRef", x.ReleaseReference), ("remarks", x.Remarks), AuditArgs(x.Audit));
        foreach (var x in g.Where(x => x.RenewalOfGuaranteeId is not null)) await Exec(db, tx, "UPDATE tender.\"Guarantees\" SET \"RenewalOfGuaranteeId\"=@renewal WHERE \"Id\"=@id", ("renewal", x.RenewalOfGuaranteeId), ("id", x.Id));
        foreach (var x in d) await Exec(db, tx, "INSERT INTO tender.\"Documents\" (\"Id\",\"TenderRecordId\",\"Category\",\"Name\",\"ReferenceNumber\",\"DocumentDate\",\"Notes\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@tender,@category,@name,@reference,@date,@notes,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("tender", x.TenderId), ("category", x.Category), ("name", x.Name), ("reference", x.Reference), ("date", x.Date), ("notes", x.Notes), AuditArgs(x.Audit));
        foreach (var x in c) await Exec(db, tx, "INSERT INTO tender.\"Competitors\" (\"Id\",\"TenderRecordId\",\"BidderName\",\"QuotedAmount\",\"Rank\",\"IsOwnBid\",\"Remarks\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@tender,@name,@amount,@rank,@own,@remarks,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("tender", x.TenderId), ("name", x.Name), ("amount", x.Amount), ("rank", x.Rank), ("own", x.Own), ("remarks", x.Remarks), AuditArgs(x.Audit));
        foreach (var x in i) await Exec(db, tx, "INSERT INTO tender.\"TenderItems\" (\"Id\",\"TenderRecordId\",\"Description\",\"ItemCode\",\"Specification\",\"Quantity\",\"Unit\",\"UnitRate\",\"EstimatedRate\",\"CostRate\",\"Brand\",\"CountryOfOrigin\",\"DeliveryDays\",\"SortOrder\",\"Remarks\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@tender,@description,@code,@spec,@quantity,@unit,@rate,@estimate,@cost,@brand,@country,@delivery,@sort,@remarks,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("tender", x.TenderId), ("description", x.Description), ("code", x.Code), ("spec", x.Specification), ("quantity", x.Quantity), ("unit", x.Unit ?? "each"), ("rate", x.Rate), ("estimate", x.Estimated), ("cost", x.Cost), ("brand", x.Brand), ("country", x.Country), ("delivery", x.Delivery), ("sort", x.Sort), ("remarks", x.Remarks), AuditArgs(x.Audit));
        foreach (var x in p) await Exec(db, tx, "INSERT INTO tender.\"Projects\" (\"Id\",\"Code\",\"Name\",\"ClientName\",\"Description\",\"Location\",\"StartDate\",\"TargetEndDate\",\"ActualEndDate\",\"ContractValue\",\"Budget\",\"Status\",\"Priority\",\"ManagerUserId\",\"ManagerName\",\"ContactPerson\",\"ContactPhone\",\"ContactEmail\",\"Notes\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@code,@name,@client,@description,@location,@start,@target,@actual,@contract,@budget,@status,@priority,@managerId,@managerName,@contact,@phone,@email,@notes,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("code", x.Code), ("name", x.Name), ("client", x.Client), ("description", x.Description), ("location", x.Location), ("start", x.Start), ("target", x.Target), ("actual", x.Actual), ("contract", x.Contract), ("budget", x.Budget), ("status", x.Status), ("priority", x.Priority), ("managerId", x.ManagerId), ("managerName", x.ManagerName), ("contact", x.ContactPerson), ("phone", x.ContactPhone), ("email", x.ContactEmail), ("notes", x.Notes), AuditArgs(x.Audit));
        foreach (var x in tasks.Where(x => x.ProjectId is not null)) await Exec(db, tx, "INSERT INTO tender.\"ProjectTasks\" (\"Id\",\"ProjectId\",\"Title\",\"Description\",\"DueDate\",\"CompletedOn\",\"Status\",\"PercentComplete\",\"AssigneeUserId\",\"AssigneeName\",\"StartDate\",\"Priority\",\"EstimatedHours\",\"ActualHours\",\"SortOrder\",\"Notes\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@project,@title,@description,@due,@completed,@status,@progress,@assigneeId,@assigneeName,@start,@priority,@estimated,@actual,@sort,@notes,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("project", x.ProjectId!.Value), ("title", x.Title), ("description", x.Description), ("due", x.Due), ("completed", x.Completed), ("status", x.Status), ("progress", x.Progress), ("assigneeId", x.AssigneeId), ("assigneeName", x.AssigneeName), ("start", x.Start), ("priority", x.Priority), ("estimated", x.Estimated), ("actual", x.Actual), ("sort", x.Sort), ("notes", x.Notes), AuditArgs(x.Audit));
        foreach (var x in tasks.Where(x => x.TenderId is not null)) await Exec(db, tx, "INSERT INTO tender.\"TenderTasks\" (\"Id\",\"TenderRecordId\",\"Title\",\"Description\",\"StartDate\",\"DueDate\",\"CompletedOn\",\"Status\",\"PercentComplete\",\"Priority\",\"EstimatedHours\",\"ActualHours\",\"SortOrder\",\"AssigneeUserId\",\"AssigneeName\",\"Notes\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@tender,@title,@description,@start,@due,@completed,@status,@progress,@priority,@estimated,@actual,@sort,@assigneeId,@assigneeName,@notes,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("tender", x.TenderId!.Value), ("title", x.Title), ("description", x.Description), ("start", x.Start), ("due", x.Due), ("completed", x.Completed), ("status", x.Status), ("progress", x.Progress), ("priority", x.Priority), ("estimated", x.Estimated), ("actual", x.Actual), ("sort", x.Sort), ("assigneeId", x.AssigneeId), ("assigneeName", x.AssigneeName), ("notes", x.Notes), AuditArgs(x.Audit));
        foreach (var x in milestones) await Exec(db, tx, "INSERT INTO tender.\"ProjectMilestones\" (\"Id\",\"ProjectId\",\"Name\",\"Description\",\"DueDate\",\"AchievedDate\",\"Status\",\"PaymentAmount\",\"SortOrder\",\"Notes\",\"CreatedUtc\",\"CreatedBy\",\"ModifiedUtc\",\"ModifiedBy\",\"IsDeleted\",\"DeletedUtc\",\"DeletedBy\") VALUES (@id,@project,@name,@description,@due,@achieved,@status,@payment,@sort,@notes,@created,@createdBy,@modified,@modifiedBy,@deleted,@deletedAt,@deletedBy)", ("id", x.Id), ("project", x.ProjectId), ("name", x.Name), ("description", x.Description), ("due", x.Due), ("achieved", x.Achieved), ("status", x.Status), ("payment", x.Payment), ("sort", x.Sort), ("notes", x.Notes), AuditArgs(x.Audit));
        foreach (var table in new[] { "Tenders", "Guarantees", "Documents", "Competitors", "TenderItems", "Projects", "ProjectTasks", "TenderTasks", "ProjectMilestones" }) await Exec(db, tx, $"SELECT setval(pg_get_serial_sequence('tender.\"{table}\"','Id'),GREATEST(COALESCE((SELECT MAX(\"Id\") FROM tender.\"{table}\"),1),1),true)");
        await using var check = new NpgsqlCommand("SELECT (SELECT COUNT(*) FROM tender.\"Tenders\"),(SELECT COUNT(*) FROM tender.\"Guarantees\"),(SELECT COUNT(*) FROM tender.\"Documents\"),(SELECT COUNT(*) FROM tender.\"Competitors\"),(SELECT COUNT(*) FROM tender.\"TenderItems\"),(SELECT COUNT(*) FROM tender.\"Projects\"),(SELECT COUNT(*) FROM tender.\"ProjectTasks\"),(SELECT COUNT(*) FROM tender.\"TenderTasks\"),(SELECT COUNT(*) FROM tender.\"ProjectMilestones\")", db, tx);
        await using var reader = await check.ExecuteReaderAsync(); await reader.ReadAsync();
        var expected = new[] { t.Count, g.Count, d.Count, c.Count, i.Count, p.Count, tasks.Count(x => x.ProjectId is not null), tasks.Count(x => x.TenderId is not null), milestones.Count };
        for (var index = 0; index < expected.Length; index++) if (reader.GetInt64(index) != expected[index]) throw new InvalidOperationException("Tender count reconciliation failed.");
        await tx.CommitAsync();
    }

    private static async Task Exec(NpgsqlConnection db, NpgsqlTransaction tx, string sql, params object[] args)
    {
        await using var c = new NpgsqlCommand(sql, db, tx);
        foreach (var arg in args)
        {
            if (arg is ValueTuple<string, object?> one) c.Parameters.AddWithValue(one.Item1, one.Item2 ?? DBNull.Value);
            else if (arg is (string Name, object? Value)[] many) foreach (var (name, value) in many) c.Parameters.AddWithValue(name, value ?? DBNull.Value);
            else throw new InvalidOperationException("Invalid importer parameter.");
        }
        await c.ExecuteNonQueryAsync();
    }
    private static (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit(DbDataReader r) => (DT(r, "CreatedAtUtc") ?? throw new InvalidDataException("Missing CreatedAtUtc."), S(r, "CreatedBy"), DT(r, "ModifiedAtUtc"), S(r, "ModifiedBy"), B(r, "IsDeleted"), DT(r, "DeletedAtUtc"), S(r, "DeletedBy"));
    private static (string Name, object? Value)[] AuditArgs((DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) a) => [("created", a.Created), ("createdBy", a.CreatedBy), ("modified", a.Modified), ("modifiedBy", a.ModifiedBy), ("deleted", a.Deleted), ("deletedAt", a.DeletedAt), ("deletedBy", a.DeletedBy)];
    private static int I(DbDataReader r, string n) => Convert.ToInt32(r[n]); private static int? NI(DbDataReader r, string n) => r[n] is DBNull ? null : Convert.ToInt32(r[n]); private static decimal D(DbDataReader r, string n) => Convert.ToDecimal(r[n]); private static decimal? ND(DbDataReader r, string n) => r[n] is DBNull ? null : Convert.ToDecimal(r[n]); private static string? S(DbDataReader r, string n) => r[n] is DBNull ? null : Convert.ToString(r[n]); private static bool B(DbDataReader r, string n) => Convert.ToBoolean(r[n]); private static DateOnly? Date(DbDataReader r, string n) => r[n] is DBNull ? null : DateOnly.FromDateTime(Convert.ToDateTime(r[n])); private static DateTime? DT(DbDataReader r, string n) => r[n] is DBNull ? null : Convert.ToDateTime(r[n]);
    private static int Fail(string message) { Console.Error.WriteLine(message); return 2; }

    private sealed record TenderRow(int Id, string Number, string Title, string Authority, string? Department, string? Description, decimal Estimate, decimal? Fee, decimal? Emd, bool Exempt, string? ExemptReason, decimal? Performance, decimal? Retention, int Submission, string? Portal, int? Validity, DateOnly? Publish, DateOnly? Deadline, DateOnly? Technical, DateOnly? Financial, int Status, int? Rank, decimal? L1, decimal? Awarded, DateOnly? AwardDate, string? WorkOrder, DateOnly? ContractStart, DateOnly? ContractEnd, int? Completion, int? Defect, string? Terms, string? ContactPerson, string? ContactPhone, string? ContactEmail, string? Notes, (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit);
    private sealed record GuaranteeRow(int Id, int TenderId, int Type, int InstrumentType, string? Bank, string? Branch, string? BankContactPerson, string? BankContactPhone, string? Number, decimal Amount, DateOnly? Issue, DateOnly? Expiry, DateOnly? Claim, int Status, DateOnly? Release, string? ReleaseReference, string? Remarks, decimal? Charges, int? RenewalOfGuaranteeId, (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit);
    private sealed record DocumentRow(int Id, int TenderId, int Category, string Name, string? Reference, DateOnly? Date, string? Notes, (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit);
    private sealed record CompetitorRow(int Id, int TenderId, string Name, decimal Amount, int? Rank, bool Own, string? Remarks, (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit);
    private sealed record ItemRow(int Id, int TenderId, string? Code, string Description, string? Specification, string? Unit, decimal Quantity, decimal Rate, decimal? Estimated, decimal? Cost, string? Brand, string? Country, int? Delivery, int Sort, string? Remarks, (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit);
    private sealed record ProjectRow(int Id, string Code, string Name, string? Client, string? Description, string? Location, string? ManagerId, string? ManagerName, decimal? Contract, decimal? Budget, DateOnly? Start, DateOnly? Target, DateOnly? Actual, int Status, int Priority, string? ContactPerson, string? ContactPhone, string? ContactEmail, string? Notes, (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit);
    private sealed record TaskRow(int Id, int? ProjectId, int? TenderId, string Title, string? Description, string? AssigneeId, string? AssigneeName, DateOnly? Start, DateOnly? Due, DateOnly? Completed, int Status, int Priority, int Progress, decimal? Estimated, decimal? Actual, int Sort, string? Notes, (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit);
    private sealed record MilestoneRow(int Id, int ProjectId, string Name, string? Description, DateOnly? Due, DateOnly? Achieved, int Status, decimal? Payment, int Sort, string? Notes, (DateTime Created, string? CreatedBy, DateTime? Modified, string? ModifiedBy, bool Deleted, DateTime? DeletedAt, string? DeletedBy) Audit);
}
