using MeiErp.Platform.Reporting;
using MeiErp.Platform.Kernel;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MeiErp.Modules.Tender;

public static class TenderReports
{
    public static IServiceCollection AddTenderReports(this IServiceCollection services)
    {
        services.AddSingleton<ReportDefinition>(sp=>Pipeline(sp));services.AddSingleton<ReportDefinition>(sp=>WinLoss(sp));services.AddSingleton<ReportDefinition>(sp=>Authority(sp));services.AddSingleton<ReportDefinition>(sp=>Security(sp));services.AddSingleton<ReportDefinition>(sp=>Expiry(sp));services.AddSingleton<ReportDefinition>(sp=>BankExposure(sp));return services;
    }
    private static ReportDefinition Make(IServiceProvider sp,string key,string name,string description,Func<TenderDbContext,ReportRequest,CancellationToken,Task<ReportResult>> run)=>new(){Key="tender."+key,Name=name,Description=description,ModuleKey=TenderModule.Key,Group="Tender",Permission=TenderModule.ReportsView,Uses=ReportFilters.None,Run=async(r,c)=>{using var scope=sp.CreateScope();r=r with{AsAt=r.AsAt??scope.ServiceProvider.GetRequiredService<IClock>().Today};return await run(scope.ServiceProvider.GetRequiredService<TenderDbContext>(),r,c);}};
    private static ReportDefinition Pipeline(IServiceProvider sp)=>Make(sp,"pipeline","Tender Pipeline by Status","Open and decided bid value by state.",async(db,r,ct)=>{var rows=await db.Tenders.AsNoTracking().GroupBy(x=>x.Status).Select(g=>new{Status=g.Key,Count=g.Count(),Value=g.Sum(x=>x.EstimatedValue??0)}).OrderBy(x=>x.Status).ToListAsync(ct);return Result([C("status","Status",ReportValueKind.Status),C("count","Count",ReportValueKind.Number),C("value","Estimated value",ReportValueKind.Money)],rows.Select(x=>Row(null,("status",x.Status),("count",x.Count),("value",x.Value))),("count",rows.Sum(x=>x.Count)),("value",rows.Sum(x=>x.Value)));});
    private static ReportDefinition WinLoss(IServiceProvider sp)=>Make(sp,"win-loss","Win / Loss Analysis","Decided tenders and win rate.",async(db,r,ct)=>{var rows=await db.Tenders.AsNoTracking().Where(x=>x.Status==TenderStatus.Won||x.Status==TenderStatus.Lost).OrderByDescending(x=>x.Id).ToListAsync(ct);var won=rows.Count(x=>x.Status==TenderStatus.Won);return new(){Columns=[C("reference","Reference"),C("title","Title"),C("client","Issuing authority"),C("outcome","Outcome",ReportValueKind.Status),C("estimated","Estimated",ReportValueKind.Money),C("bid","Bid total",ReportValueKind.Money)],Rows=[..rows.Select(x=>Row("/tender/tenders",("reference",x.Reference),("title",x.Title),("client",x.ClientName),("outcome",x.Status),("estimated",x.EstimatedValue),("bid",x.ItemsTotal)))],Header=[new("Win rate",rows.Count==0?"—":$"{won*100m/rows.Count:N0}% ({won}/{rows.Count})")]};});
    private static ReportDefinition Authority(IServiceProvider sp)=>Make(sp,"authority","Value by Issuing Authority","Tender count, wins, and estimated value by client.",async(db,r,ct)=>{var rows=await db.Tenders.AsNoTracking().GroupBy(x=>x.ClientName).Select(g=>new{Name=g.Key,Count=g.Count(),Won=g.Count(x=>x.Status==TenderStatus.Won),Value=g.Sum(x=>x.EstimatedValue??0)}).OrderByDescending(x=>x.Value).ToListAsync(ct);return Result([C("authority","Authority"),C("count","Tenders",ReportValueKind.Number),C("won","Won",ReportValueKind.Number),C("value","Estimated value",ReportValueKind.Money)],rows.Select(x=>Row(null,("authority",x.Name),("count",x.Count),("won",x.Won),("value",x.Value))),("value",rows.Sum(x=>x.Value)));});
    private static ReportDefinition Security(IServiceProvider sp)=>Make(sp,"security-register","Security / Guarantee Register","All EMDs, bonds, and guarantees.",async(db,r,ct)=>{var rows=await db.Guarantees.AsNoTracking().Include(x=>x.Tender).OrderByDescending(x=>x.IssuedOn).ToListAsync(ct);return Result([C("tender","Tender"),C("kind","Type"),C("bank","Bank / number"),C("amount","Amount",ReportValueKind.Money),C("issued","Issue",ReportValueKind.Date),C("expiry","Expiry",ReportValueKind.Date),C("status","Status",ReportValueKind.Status)],rows.Select(x=>Row("/tender/tenders",("tender",x.Tender?.Reference),("kind",x.Kind),("bank",$"{x.BankName} {x.InstrumentNumber}".Trim()),("amount",x.Amount),("issued",x.IssuedOn),("expiry",x.ExpiresOn),("status",x.ReleasedOn is null?"Active":"Released"))),("amount",rows.Sum(x=>x.Amount)));});
    private static ReportDefinition Expiry(IServiceProvider sp)=>Make(sp,"expiry","Guarantees Expiring Soon","Outstanding instruments due within 60 days, including overdue.",async(db,r,ct)=>{var today=r.AsAt!.Value;var cutoff=today.AddDays(60);var rows=await db.Guarantees.AsNoTracking().Include(x=>x.Tender).Where(x=>x.ReleasedOn==null&&x.ExpiresOn<=cutoff).OrderBy(x=>x.ExpiresOn).ToListAsync(ct);return Result([C("tender","Tender"),C("kind","Type"),C("bank","Bank / number"),C("amount","Amount",ReportValueKind.Money),C("expiry","Expiry",ReportValueKind.Date),C("remaining","Remaining")],rows.Select(x=>Row("/tender/tenders",("tender",x.Tender?.Reference),("kind",x.Kind),("bank",$"{x.BankName} {x.InstrumentNumber}".Trim()),("amount",x.Amount),("expiry",x.ExpiresOn),("remaining",x.ExpiresOn is null?"—":x.ExpiresOn<today?"OVERDUE":$"{x.ExpiresOn.Value.DayNumber-today.DayNumber}d"))),("amount",rows.Sum(x=>x.Amount)));});
    private static ReportDefinition BankExposure(IServiceProvider sp)=>Make(sp,"bank-exposure","Bank-wise Exposure","Outstanding guarantee value by bank.",async(db,r,ct)=>{var rows=await db.Guarantees.AsNoTracking().Where(x=>x.ReleasedOn==null).GroupBy(x=>x.BankName??"(unspecified)").Select(g=>new{Bank=g.Key,Count=g.Count(),Amount=g.Sum(x=>x.Amount)}).OrderByDescending(x=>x.Amount).ToListAsync(ct);return Result([C("bank","Bank"),C("count","Instruments",ReportValueKind.Number),C("amount","Amount",ReportValueKind.Money)],rows.Select(x=>Row(null,("bank",x.Bank),("count",x.Count),("amount",x.Amount))),("amount",rows.Sum(x=>x.Amount)));});
    private static ReportColumn C(string key,string name,ReportValueKind kind=ReportValueKind.Text)=>new(key,name,kind);private static ReportRow Row(string? url,params(string Key,object? Value)[] values)=>new(values.ToDictionary(x=>x.Key,x=>x.Value),url);private static ReportResult Result(IReadOnlyList<ReportColumn> cols,IEnumerable<ReportRow> rows,params(string Key,decimal Value)[] totals)=>new(){Columns=cols,Rows=rows.ToList(),Totals=totals.Select(x=>new ReportTotal(x.Key,x.Value)).ToList()};
}
